Summary: A real mode 80x86 assembler and linker
Name: dev86
Version: 0.16.20
Release: 1%{?dist}
License: GPL+ and GPLv2+ and LGPLv2+
Group: Development/Languages
URL: http://v3.sk/~lkundrak/dev86/
Source: http://v3.sk/~lkundrak/dev86/archive/Dev86src-%{version}.tar.gz
Patch0: dev86-noelks.patch
#Patch1: dev86-64bit.patch
Patch2: dev86-nostrip.patch
Patch4: dev86-long.patch

# don't try to strip binaries generated by dev86 unknown to /usr/bin/strip
%define __os_install_post    /usr/lib/rpm/brp-compress /usr/lib/rpm/brp-strip %{__strip} /usr/lib/rpm/brp-strip-comment-note %{__strip} %{__objdump} %{nil}

%description
The dev86 package provides an assembler and linker for real mode 80x86
instructions. You'll need to have this package installed in order to
build programs that run in real mode, including LILO and the kernel's
bootstrapping code, from their sources.

You should install dev86 if you intend to build programs that run in real
mode from their source code.

%prep
%setup -q
%patch0 -p1 -b .noelks
#%if 0%{?__isa_bits} == 64
#%patch1 -p1 -b .64bit
#%endif
%patch2 -p1 -b .nostrip
%patch4 -p1 -b .long

%build
export CPPFLAGS=""
export SHELL=/bin/bash
make -j1 bcc86 unproto copt as86 ld86 CFLAGS="$CFLAGS" CC="${CC:-gcc}" \
	NATIVE='-DA_OUT_INCL=\"../libc/include/a.out.h\"' 
make -C cpp CFLAGS="$CFLAGS"  CC="${CC:-gcc}"
make -C ar CFLAGS="$CFLAGS" CC="${CC:-gcc}"
make -C ld CFLAGS="$CFLAGS" CC="${CC:-gcc}"
make -j1 DIST=%{buildroot} CC="${CC:-gcc}"

%install
rm -rf ${RPM_BUILD_ROOT}

make	DIST=${RPM_BUILD_ROOT} \
	MANDIR=/usr/share/man \
	LIBDIR=%{_libdir}/bcc \
	INCLDIR=%{_libdir}/bcc \
	LOCALPREFIX=%{_prefix} \
	install install-man

# preserve READMEs
for i in bootblocks copt dis88 unproto bin86 ; do cp $i/README README.$i ; done
cp bin86/README-0.4 README-0.4.bin86
cp bin86/ChangeLog ChangeLog.bin86
mv libc/COPYING COPYING.LGPL

cd ${RPM_BUILD_ROOT}%{_bindir}
rm -f nm86 size86
ln -s objdump86 nm86
ln -s objdump86 size86
cd ..

%clean
rm -rf ${RPM_BUILD_ROOT}

%files
%defattr(-,root,root,-)
%doc README MAGIC Contributors README.bootblocks README.copt README.dis88
%doc README.unproto README-0.4.bin86 README.bin86 ChangeLog.bin86 COPYING
%doc COPYING.LGPL
%dir %{_libdir}/bcc
%{_bindir}/bcc
%{_bindir}/ar86
%{_bindir}/as86
%{_bindir}/ld86
%{_bindir}/objdump86
%{_bindir}/nm86
%{_bindir}/size86
%{_libdir}/bcc/*
%{_mandir}/man1/*

%changelog
