#!/bin/sh

package=$1
verbose=$2
tee=''

if [ "$(id -u)" != "0" ]; then
   echo 'This script must be run as root, use sudo or su -c "./rootme"' 1>&2
   exit 1
fi

rpmdir=`pwd`/rpms
chroot_name='chroot-x86_64'

if [ ! "$(ls -A $chroot_name/proc)" ]; then
   mkdir -pv {dev,proc,sys}
   mount -v --bind /dev $chroot_name/dev
   mount -vt proc proc $chroot_name/proc
   mount -vt sysfs sysfs $chroot_name/sys
fi

if [ -h $chroot_name/dev/shm ]; then
  mkdir -pv $(readlink $chroot_name/dev/shm)
fi

if [ ! -f "$chroot_name/usr/bin/busybox" ]; then
   cd $chroot_name/usr/bin
   ln -s ../../bin/* .
   cd ../../../
fi

if ! grep '/root/packages/' /proc/mounts; then
        mount --bind ./unity-linux/base/packages/ $chroot_name/root/packages
fi

if ! grep '/root/rpms/' /proc/mounts; then
        mount --bind ./rpms/ $chroot_name/root/rpms
fi

if ! grep '/root/building/' /proc/mounts; then
        mount --bind ./building/ $chroot_name/root/building
fi

if [[ -n $(screen -ls | grep $package) ]]; then
	for session in $(screen -ls | grep -o '[0-9]*\.'$package); 
		do 
			screen -S "${session}" -X quit 
		done
fi
screen -dmS $package

screen -r $package -p 0 -X stuff $"chroot $chroot_name /usr/bin/bash -c 'cd /root/packages/$package/;rpmbuild -ba $package.spec 2>&1 | tee /root/rpmbuild/RPMS/logs/$package.log';exit ^M"

if [[ $verbose == "-v" ]]; then
	screen -R $package
fi
