#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo 'This script must be run as root, use sudo or su -c "./rootme"' 1>&2
   exit 1
fi

umount $(mount | grep chroot | awk '{print $3}')

if [ ! "$(mount | grep chroot | awk '{print $3}')" ]; then
	echo "All Chroot mounts removed."
else
	echo "Warning: Chroot mounts still exist."
fi
