Unity Live th is a Live CD project to let you
test Unity Linux without installing it to your
hard drive. It is also useful for rescuing
damaged systems.

In case boot troubles try following args:
 noapic        Disable the "Advanced Programmable Interrupt Controller"
 noacpi        This parameter disables the whole ACPI system
 debuginitrd   Run debug shell after initrd process


press any key to return to menu
